### PR TITLE
Use `display-line-numbers` when calculating padding.

### LINKED ISSUE #78: New Emacs 26 display-line-numbers breaks Fill-Column-Indicator
Emacs 26 has added its own built-in line numbering system that obsoletes (n)linum.

This seems incompatible with FCI. When both FCI is enabled and `setq display-line-numbers t` is set the line numbering essentially look like:

```
1| Some text         |
2| Some more text    |
3| Some more text    |
4| A line with very very long text |
5| Some more text    |
```

Where the bar on the right represents the FCI line. The Emacs built-in line numbering is the now recommended way to display line numbering, and it has essentially deprecated (n)linum mode, so I think it would be a good idea to make FCI compatible.

### PR DESCRIPTION
**Pull request by shaleh**
In Emacs 26 line number display is now built in. The mode needs to check
if `display-line-numbers` is active and when it is use
`line-number-display-width` when calculating where to show the rule.

Resolves #78.

### CODE REVIEW

**Comment by blaenk** [comment]
I can confirm this works.

**Comment by naclander** [comment]
@shaleh any chance you can make this patch compatible with #76 ?

**Comment by shaleh** [comment]
@naclander it should be possible. The lndw value would need to be applied to the column before it is multiplied for the scaling. This needs testing in text mode, graphics mode, and in emacs major modes with mixed fonts. Also, the `window-font-width` function is new in the 25.x series and #76 
 does not check if it is defined before using.

I will look into it as time allows.

**Comment by naclander** [comment]
FWIW, I wanted both both of the patches. So I ran `git am -3 display-line.patch zoom.patch` after downloading both patches manually. 

It was then trivial to fix the conflict, and both patches seem to be working fine for me now. Althoguh I haven't ran any exaustive tests, just personal usage.

Thanks again for the patch. I suspect since nothing is currently getting merged we'll be running into more conflicts in the future.

**Comment by shaleh** [comment]
Yeah, I contacted the author and have heard nothing back. One of us may need to fork it. I get that it is a total pain and a better solution needs to be found. But this is what we have for now.

**Comment by dieggsy** [comment]
@shaleh I think there's precedent for changing MELPA to point to a fork if the author of the original repo is unresponsive enough, we may want to look into that.

paging @purcell for thoughts/comments/corrections

**Comment by purcell** [comment]
> @shaleh I think there's precedent for changing MELPA to point to a fork if the author of the original repo is unresponsive enough, we may want to look into that.
> 
> paging @purcell for thoughts/comments/corrections

Yes, there's precedent for this. Ideally resolution would be if @alpaker will add one of you as a collaborator in this repo so that you can maintain it more actively. Would someone like to volunteer? Otherwise, and if the author doesn't veto it, I'll accept a MELPA pull request in a week's time to switch the MELPA recipe to point at a fork made by that volunteer.

**Comment by alpaker** [comment]
Sorry all.  I accidentally turned off notifications for this repo and so didn't received anything about this PR until I was @-mentioned.   Taking a look now.

**Comment by alpaker** [comment]
@shaleh Thanks a lot for the fix.  Sorry again for the delay.

**Comment by shaleh** [comment]
@alpaker glad to help. As I said earlier, I know this repo is a pain. I use it when hacking on Python code that is required to follow PEP8 which hard limits to 78 chars. I prefer 100 or so and the guide is helpful.

**Comment by purcell** [comment]
> Sorry all. I accidentally turned off notifications for this repo and so didn't received anything about this PR until I was @-mentioned. Taking a look now.

Awesome, thanks @alpaker! Fwiw, I've taken to adding co-committers to my repos quite freely, and it's worked out really well.

**Pull request merged**
